% Create a mask map for Unity HDRP without detail mas by copying the metallic,
% ambient occulusion, NO DETAIL MASK and smoothness into one .png file.
createStackedTexture("factorylargerocksplain_maskMap.png", ...
                     "factorylargerocksplain_metallic.png", ...
                     "factorylargerocksplain_ao.png", ...
                     zeros(250, 250, 3, 'uint8'), ... % To leave out just add zeros. 
                     "factorylargerocksplain_smoothness.png")
