% In this example I am copying the ambient occulusion, metallic,
% smoothness, and edge information into one .png file.
createStackedTexture("stackedTexture.png", ...
                     "factorylargerocksplain_ao.png", ...
                     "factorylargerocksplain_metallic.png", ....
                     "factorylargerocksplain_smoothness.png", ...
                     "factorylargerocksplain_edge.png")
                 
% Use only black in R channel                 
createStackedTexture("stackedTexture_noR.png", ...
                     zeros(250, 250, 3, 'uint8'), ...
                     "factorylargerocksplain_metallic.png", ....
                     "factorylargerocksplain_smoothness.png", ...
                     "factorylargerocksplain_edge.png")